# Generated by Django 2.2.4 on 2019-08-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member_map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='address',
            field=models.CharField(default='no value', max_length=200),
            preserve_default=False,
        ),
    ]
